[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"

